# config.py

# Detection filters
DEFAULT_MIN_SPOT_AREA = 450
DEFAULT_MAX_SPOT_AREA = 15000
DEFAULT_MIN_CIRCULARITY = 0.45
DEFAULT_MIN_SOLIDITY = 0.65

# Preprocessing
DEFAULT_BG_BLUR_K = 81
DEFAULT_CLAHE_CLIP = 2.0
DEFAULT_CLAHE_TILE = (8, 8)

# Thresholding
DEFAULT_THRESH_BLOCKSIZE = 35
DEFAULT_THRESH_C = 2

# Morphology
DEFAULT_OPEN_KERNEL = 2
DEFAULT_CLOSE_KERNEL = 3

# Defect inspection
DEFAULT_ERODE_PX = 2
DEFAULT_MAD_K = 4.5
DEFAULT_MAX_OUTLIER_FRAC = 0.16

DEFAULT_DARK_Q = 10
DEFAULT_BRIGHT_Q = 95
DEFAULT_DEFECT_AREA_FRAC = 0.03
DEFAULT_MIN_DEFECT_AREA_PX = 35